name: Deploy React App to GitHub Pages (Main Branch)

on:
  push:
    branches:
      - main  # ✅ Deploy from the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build React App
        run: |
          yarn build
          echo "Checking if build folder exists..."
          ls -la build || echo "❌ Build folder is missing!"
          mv build ../build || echo "❌ Failed to move build folder!"

      - name: Deploy to GitHub Pages (Main Branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # ✅ Deploying to main branch
          folder: build  # ✅ Deploy only the `build/` folder
          clean: true  # ✅ Clean old files
